// <auto-generated />
namespace KotProno2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class v110 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v110));
        
        string IMigrationMetadata.Id
        {
            get { return "201406081936342_v1.1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
