// <auto-generated />
namespace KotProno2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class v260 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v260));
        
        string IMigrationMetadata.Id
        {
            get { return "201607041730471_v2.6.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
