// <auto-generated />
namespace KotProno2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class v350 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v350));
        
        string IMigrationMetadata.Id
        {
            get { return "201807081344497_v3.5.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
