// <auto-generated />
namespace KotProno2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v390 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v390));
        
        string IMigrationMetadata.Id
        {
            get { return "202106301543431_v3.9.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
